<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RmFactoriesAsConfiguration\Module'                                => __DIR__ . '/Module.php',
    'RmFactoriesAsConfiguration\ConfigDrivenAbstractFactory'           => __DIR__ . '/src/ConfigDrivenAbstractFactory.php',
    'RmFactoriesAsConfiguration\ControllerConfigDrivenAbstractFactory' => __DIR__ . '/src/ControllerConfigAbstractFactory.php',
);
