<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RmFactoriesAsConfiguration\Module'                        => __DIR__ . '/Module.php',
    'RmFactoriesAsConfiguration\ConfigDrivenFactory'           => __DIR__ . '/src/ConfigDrivenFactory.php',
    'RmFactoriesAsConfiguration\ControllerConfigDrivenFactory' => __DIR__ . '/src/ControllerConfigFactory.php',
);
